import type { Product } from "./types";

export const CATEGORIES = ["All", "Extrait de Parfum", "Eau de Parfum", "Eau de Toilette"] as const;

export const PRODUCTS: Product[] = [
  {
    id: "amber-oud-royale",
    name: "Amber Oud Royale",
    subtitle: "Golden oud wrapped in warm amber",
    category: "Extrait de Parfum",
    family: "Amber Oud",
    size: "100ml",
    price: 385000,
    stock: 14,
    rating: 4.9,
    reviewsCount: 128,
    tag: "Bestseller",
    featured: true,
    palette: ["#f59e0b", "#b45309", "#7c2d12"],
    description:
      "Our signature masterpiece. Rare agarwood is aged in amber resin before blending, yielding a scent that opens bright with saffron and settles into a golden, honeyed warmth that lingers for days.",
    notes: {
      top: ["Saffron", "Bergamot", "Nutmeg"],
      heart: ["Rose absolute", "Agarwood (oud)", "Cinnamon"],
      base: ["Amber", "Sandalwood", "Vanilla", "Tonka"],
    },
    reviews: [
      {
        author: "Adaeze O.",
        rating: 5,
        date: "2026-05-12",
        text: "This is the fragrance everyone asks about. The oud is smooth, never sharp, and it lasts well past 12 hours on my skin.",
        verified: true,
      },
      {
        author: "Tunde A.",
        rating: 5,
        date: "2026-04-02",
        text: "Bought it for my wedding. Golden, regal, unforgettable. The dry-down is pure luxury.",
        verified: true,
      },
    ],
  },
  {
    id: "midnight-iris",
    name: "Midnight Iris",
    subtitle: "Powdery violet bloom under a starless sky",
    category: "Eau de Parfum",
    family: "Floral",
    size: "100ml",
    price: 215000,
    stock: 22,
    rating: 4.8,
    reviewsCount: 94,
    featured: true,
    palette: ["#a78bfa", "#7c3aed", "#4c1d95"],
    description:
      "A nocturnal floral built on rare orris root. Velvety iris and violet leaf unfold over cool cedar and white musk — sophisticated, quietly magnetic.",
    notes: {
      top: ["Iris", "Violet leaf", "Bergamot"],
      heart: ["Orris butter", "Jasmine", "Heliotrope"],
      base: ["Cedarwood", "White musk", "Ambroxan"],
    },
    reviews: [
      {
        author: "Chiamaka N.",
        rating: 5,
        date: "2026-06-01",
        text: "Powdery but not old-fashioned. It feels like moonlight. Compliments every single time.",
        verified: true,
      },
      {
        author: "Fatima B.",
        rating: 4,
        date: "2026-03-18",
        text: "Beautiful iris scent. Projects moderately — perfect for the office.",
        verified: true,
      },
    ],
  },
  {
    id: "citrus-elan",
    name: "Citrus Élan",
    subtitle: "Sparkling Mediterranean citrus, airy and bright",
    category: "Eau de Toilette",
    family: "Fresh Citrus",
    size: "100ml",
    price: 128000,
    stock: 31,
    rating: 4.6,
    reviewsCount: 67,
    tag: "New",
    palette: ["#fbbf24", "#34d399", "#0ea5e9"],
    description:
      "A burst of sun-ripened bergamot and lemon over neroli and white musk. Effervescent, clean and endlessly wearable — the perfect signature for warm weather.",
    notes: {
      top: ["Bergamot", "Lemon", "Pink grapefruit"],
      heart: ["Neroli", "Petitgrain", "Orange blossom"],
      base: ["White musk", "Vetiver", "Light cedar"],
    },
    reviews: [
      {
        author: "Daniel K.",
        rating: 5,
        date: "2026-06-20",
        text: "Like a glass of citrus soda on a hot Lagos afternoon. Fresh without being generic.",
        verified: true,
      },
    ],
  },
  {
    id: "velvet-rose-noir",
    name: "Velvet Rose Noir",
    subtitle: "Dark damask rose on a bed of patchouli",
    category: "Extrait de Parfum",
    family: "Rose",
    size: "100ml",
    price: 295000,
    stock: 11,
    rating: 4.9,
    reviewsCount: 76,
    featured: true,
    palette: ["#f472b6", "#be185d", "#500724"],
    description:
      "An uncompromising rose — heady damask absolute darkened with blackcurrant and pink pepper, resting on velvet patchouli and tonka. Dramatic, romantic, powerful.",
    notes: {
      top: ["Blackcurrant", "Pink pepper", "Lychee"],
      heart: ["Damask rose", "Peony", "Geranium"],
      base: ["Patchouli", "Tonka bean", "White musk"],
    },
    reviews: [
      {
        author: "Ngozi E.",
        rating: 5,
        date: "2026-05-30",
        text: "The rose here is jammy and deep, not soapy. One spray is enough to command a room.",
        verified: true,
      },
    ],
  },
  {
    id: "ocean-bloom",
    name: "Ocean Bloom",
    subtitle: "Salty breeze, water lilies and driftwood",
    category: "Eau de Parfum",
    family: "Aquatic",
    size: "100ml",
    price: 189000,
    stock: 18,
    rating: 4.7,
    reviewsCount: 58,
    palette: ["#22d3ee", "#0ea5e9", "#1e3a8a"],
    description:
      "The smell of a distant shore — mineral sea salt and bergamot open onto water lily and freesia, drying down to warm driftwood and ambergris.",
    notes: {
      top: ["Sea salt", "Bergamot", "Marine accord"],
      heart: ["Water lily", "Freesia", "Lotus"],
      base: ["Driftwood", "Ambergris", "Grey amber"],
    },
    reviews: [
      {
        author: "Ibrahim S.",
        rating: 5,
        date: "2026-04-25",
        text: "Fresh, aquatic and calming. Feels like a beach holiday in a bottle.",
        verified: true,
      },
    ],
  },
  {
    id: "saffron-smoke",
    name: "Saffron Smoke",
    subtitle: "Incense, leather and glowing saffron",
    category: "Extrait de Parfum",
    family: "Smoky Spice",
    size: "100ml",
    price: 340000,
    stock: 9,
    rating: 4.8,
    reviewsCount: 83,
    tag: "Limited",
    palette: ["#ef4444", "#7f1d1d", "#1c1917"],
    description:
      "Cathedral incense and supple leather wrapped around radiant saffron. Smoky, intimate and undeniably luxurious — for evenings that matter.",
    notes: {
      top: ["Cardamom", "Saffron", "Black pepper"],
      heart: ["Frankincense", "Leather", "Cypriol"],
      base: ["Smoked woods", "Musk", "Labdanum"],
    },
    reviews: [
      {
        author: "Yusuf M.",
        rating: 5,
        date: "2026-02-14",
        text: "Smoky in the best way. It has real presence — I can still smell it on my jacket a week later.",
        verified: true,
      },
    ],
  },
  {
    id: "white-santal",
    name: "White Santal",
    subtitle: "Creamy sandalwood softened by fig",
    category: "Eau de Parfum",
    family: "Woody",
    size: "100ml",
    price: 198000,
    stock: 16,
    rating: 4.8,
    reviewsCount: 112,
    tag: "Bestseller",
    featured: true,
    palette: ["#e2e8f0", "#cbd5e1", "#94a3b8"],
    description:
      "A cult-favourite woody skin scent. Creamy sandalwood and cashmere woods are lifted by green fig leaf — soft, warm and incredibly addictive.",
    notes: {
      top: ["Fig leaf", "Mandarin", "Cardamom"],
      heart: ["Sandalwood", "Orris", "Coconut milk"],
      base: ["Cashmere wood", "White musk", "Tonka"],
    },
    reviews: [
      {
        author: "Aisha R.",
        rating: 5,
        date: "2026-06-08",
        text: "My everyday scent. It hugs the skin beautifully and layers with everything.",
        verified: true,
      },
      {
        author: "Kelechi J.",
        rating: 5,
        date: "2026-03-02",
        text: "Creamy, woody, comforting. Got my mum and my sister hooked too.",
        verified: true,
      },
    ],
  },
  {
    id: "neroli-solaire",
    name: "Neroli Solaire",
    subtitle: "Golden orange blossom in the sun",
    category: "Eau de Toilette",
    family: "Floral Fresh",
    size: "100ml",
    price: 142000,
    stock: 26,
    rating: 4.7,
    reviewsCount: 49,
    tag: "New",
    palette: ["#fdba74", "#fb923c", "#f59e0b"],
    description:
      "Sunshine captured in a bottle. Bitter orange blossom and neroli sparkle over white amber and musk — bright, joyful, radiant.",
    notes: {
      top: ["Neroli", "Petitgrain", "Mandarin"],
      heart: ["Orange blossom", "Tuberose", "Honeysuckle"],
      base: ["White amber", "Musk", "Blond woods"],
    },
    reviews: [
      {
        author: "Temilade F.",
        rating: 5,
        date: "2026-06-25",
        text: "Happiness in a spray. The orange blossom is photorealistic.",
        verified: true,
      },
    ],
  },
  {
    id: "noir-absolu",
    name: "Noir Absolu",
    subtitle: "Dark cacao, oud and night vanilla",
    category: "Extrait de Parfum",
    family: "Oriental",
    size: "100ml",
    price: 420000,
    stock: 6,
    rating: 5.0,
    reviewsCount: 41,
    tag: "Bestseller",
    featured: true,
    palette: ["#1e1b4b", "#312e81", "#6d28d9"],
    description:
      "Our darkest and most opulent creation. Bitter cacao and oud meet black vanilla and labdanum in a brooding, hypnotic oriental that feels almost alive.",
    notes: {
      top: ["Bergamot", "Davana", "Rum"],
      heart: ["Oud", "Cacao", "Turkish rose"],
      base: ["Black vanilla", "Labdanum", "Dark amber"],
    },
    reviews: [
      {
        author: "Obinna C.",
        rating: 5,
        date: "2026-05-05",
        text: "The most expensive thing I own that isn't a car, and worth every naira. A masterpiece.",
        verified: true,
      },
    ],
  },
  {
    id: "green-fig",
    name: "Green Fig",
    subtitle: "Crisp green fig leaves and soft cedar",
    category: "Eau de Parfum",
    family: "Green",
    size: "100ml",
    price: 176000,
    stock: 13,
    rating: 4.6,
    reviewsCount: 37,
    palette: ["#4ade80", "#16a34a", "#14532d"],
    description:
      "A stroll through a fig orchard at dawn. Green, dewy and quietly woody — fresh fig and galbanum over vetiver and cedar.",
    notes: {
      top: ["Fig", "Galbanum", "Lime"],
      heart: ["Fig leaf", "Vetiver", "Green tea"],
      base: ["Cedarwood", "Musk", "Oakmoss"],
    },
    reviews: [
      {
        author: "Zainab H.",
        rating: 5,
        date: "2026-04-11",
        text: "Green and clean without being sporty. Perfect for daytime.",
        verified: true,
      },
    ],
  },
  {
    id: "rose-damascena",
    name: "Rose Damascena",
    subtitle: "Two thousand petals, one bottle",
    category: "Extrait de Parfum",
    family: "Rose",
    size: "100ml",
    price: 310000,
    stock: 8,
    rating: 4.9,
    reviewsCount: 65,
    palette: ["#fb7185", "#e11d48", "#881337"],
    description:
      "Distilled from hand-picked Damascena roses at dawn. Lychee and raspberry brighten a lush, dewy rose heart over amberwood and white musk.",
    notes: {
      top: ["Lychee", "Raspberry", "Pink pepper"],
      heart: ["Damascena rose", "Geranium", "Peony"],
      base: ["Amberwood", "White musk", "Soft patchouli"],
    },
    reviews: [
      {
        author: "Amara D.",
        rating: 5,
        date: "2026-05-22",
        text: "This is THE rose. Romantic, rich and completely natural smelling.",
        verified: true,
      },
    ],
  },
  {
    id: "vanille-orchidee",
    name: "Vanille Orchidée",
    subtitle: "Bourbon vanilla wrapped in orchid",
    category: "Eau de Parfum",
    family: "Gourmand",
    size: "100ml",
    price: 168000,
    stock: 21,
    rating: 4.7,
    reviewsCount: 73,
    tag: "New",
    palette: ["#fde68a", "#f59e0b", "#b45309"],
    description:
      "Gourmand, golden and comforting. Madagascan bourbon vanilla and orchid are warmed by tonka and benzoin — dessert, but make it couture.",
    notes: {
      top: ["Mandarin", "Pink pepper", "Pear"],
      heart: ["Orchid", "Jasmine", "Heliotrope"],
      base: ["Bourbon vanilla", "Tonka", "Benzoin"],
    },
    reviews: [
      {
        author: "Simi O.",
        rating: 5,
        date: "2026-06-15",
        text: "Delicious but refined. People keep asking what I'm wearing, and then ask where to buy it.",
        verified: true,
      },
    ],
  },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export const BEST_SELLERS = PRODUCTS.filter((p) => p.tag === "Bestseller");
export const NEW_ARRIVALS = PRODUCTS.filter((p) => p.tag === "New");
export const FEATURED = PRODUCTS.filter((p) => p.featured);
